version: '3'

services:

  nginx:
    container_name: api-resources-nginx
    image: nginx
    volumes:
      - ../..:/api-resources
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - default
      - nginx-frontproxy

  php:
    container_name: api-resources-php
    hostname: api-resources-server
    build: ./php
    image: api-resources/php
    working_dir: /api-resources/example/backend
    volumes:
      - ../..:/api-resources
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ts:
    container_name: api-resources-ts
    hostname: api-resources-ts
    image: api-resources/node
    working_dir: /client
    volumes:
      - ../../api-resources-client:/client
    command: "npm run dev"

  vue:
    container_name: api-resources-vue
    hostname: api-resources-client
    build: ./node
    image: api-resources/node
    working_dir: /api-resources/example/frontend
    volumes:
      - ../..:/api-resources

  mysql:
    container_name: api-resources-mysql
    image: mariadb
    volumes:
      - api-resources-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
    ports:
      - '23306:3306'


networks:
  nginx-frontproxy:
    external: true

volumes:
  api-resources-mysql:
    driver: local
