version: '3'

services:

  nginx:
    container_name: api-resources-nginx
    image: nginx
    volumes:
      - ../..:/api-resources
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
      - php
    networks:
      - api-resources-network

  php:
    container_name: api-resources-php
    hostname: api-resources-server
    build: ./php
    image: api-resources/php
    working_dir: /api-resources/example/backend
    volumes:
      - ../..:/api-resources
    networks:
      - api-resources-network

  ts:
    container_name: api-resources-ts
    hostname: api-resources-ts
    image: api-resources/node
    working_dir: /client
    volumes:
      - ../../api-resources-client:/client
    command: "npm run dev"
    networks:
      - api-resources-network
    # logging:
    #     driver: none

  vue:
    container_name: api-resources-vue
    hostname: api-resources-client
    build: ./node
    image: api-resources/node
    working_dir: /api-resources/example/frontend
    volumes:
      - ../..:/api-resources
    networks:
      - api-resources-network
    # logging:
    #     driver: none

  mysql:
    container_name: api-resources-mysql
    image: mariadb
    restart: always
    volumes:
      - api-resources-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
    networks:
      - api-resources-network

  adminer:
    container_name: api-resources-adminer
    image: adminer
    restart: always
    networks:
      - api-resources-network

networks:
  api-resources-network:
      driver: bridge

volumes:
  api-resources-mysql:
    driver: local
